/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cih;

/**
 *
 * @author NTM
 */
public class JPGrade extends javax.swing.JPanel {

    /**
     * Creates new form JPTurma
     */
    public JPGrade() {
        initComponents();
        this.tblTurma.setRowHeight(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTurma = new javax.swing.JTable();
        lblSexta = new javax.swing.JLabel();
        lblQuinta = new javax.swing.JLabel();
        lblTerca = new javax.swing.JLabel();
        lblQuarta = new javax.swing.JLabel();
        lblSegunda = new javax.swing.JLabel();
        lblTurma = new javax.swing.JLabel();
        separadorTurma = new javax.swing.JSeparator();
        lblNoturno = new javax.swing.JLabel();
        lblVespertino = new javax.swing.JLabel();
        lblMatutino = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 0));

        tblTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Aula 1", "Aula 1", "Aula 1", "Aula 1", "Aula 1", "Aula 1", "Aula 1 ", "Título 8", "Título 9", "Título 10", "Título 11", "Título 12", "Título 13", "Título 14", "Título 15", "Título 16", "Título 17", "Título 18"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTurma);

        lblSexta.setText("Sexta");

        lblQuinta.setText("Quinta");

        lblTerca.setText("Terça");

        lblQuarta.setText("Quarta");

        lblSegunda.setText("Segunda");

        lblTurma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTurma.setText("Turma/Professor");

        lblNoturno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNoturno.setText("Noturno");

        lblVespertino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVespertino.setText("Vespertino");

        lblMatutino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMatutino.setText("Matutino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblQuinta)
                    .addComponent(lblSexta)
                    .addComponent(lblQuarta)
                    .addComponent(lblTerca)
                    .addComponent(lblTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSegunda)
                    .addComponent(separadorTurma, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblMatutino)
                        .addGap(81, 81, 81)
                        .addComponent(lblVespertino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(lblNoturno)
                        .addGap(118, 118, 118))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatutino)
                    .addComponent(lblVespertino)
                    .addComponent(lblNoturno)
                    .addComponent(lblTurma))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(separadorTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSegunda)
                        .addGap(18, 18, 18)
                        .addComponent(lblTerca)
                        .addGap(18, 18, 18)
                        .addComponent(lblQuarta)
                        .addGap(18, 18, 18)
                        .addComponent(lblQuinta)
                        .addGap(18, 18, 18)
                        .addComponent(lblSexta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMatutino;
    private javax.swing.JLabel lblNoturno;
    private javax.swing.JLabel lblQuarta;
    private javax.swing.JLabel lblQuinta;
    private javax.swing.JLabel lblSegunda;
    private javax.swing.JLabel lblSexta;
    private javax.swing.JLabel lblTerca;
    private javax.swing.JLabel lblTurma;
    private javax.swing.JLabel lblVespertino;
    private javax.swing.JSeparator separadorTurma;
    private javax.swing.JTable tblTurma;
    // End of variables declaration//GEN-END:variables
}
